In [66]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


Introduction Tesors

creating tensors

torch.Tensor -> https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor

In [67]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [68]:
scalar.ndim

0

In [69]:
# Get tensor back as python init
scalar.item()

7

In [70]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [71]:
vector.ndim

1

In [72]:
vector.shape

torch.Size([2])

In [73]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [74]:
MATRIX.ndim

2

In [75]:
MATRIX[1]

tensor([ 9, 10])

In [76]:
MATRIX.shape

torch.Size([2, 2])

In [77]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [78]:
TENSOR.ndim

3

In [79]:
TENSOR.shape

torch.Size([1, 3, 3])

In [80]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [81]:
5*10*10

500

In [82]:
## Creating random tensors of sizes
random_tensor = torch.rand(5, 10)
random_tensor

tensor([[0.3431, 0.4392, 0.3035, 0.6537, 0.8372, 0.7567, 0.9930, 0.3672, 0.7250,
         0.8128],
        [0.8740, 0.9653, 0.8135, 0.2233, 0.6043, 0.3198, 0.5131, 0.1661, 0.1687,
         0.3614],
        [0.2178, 0.9139, 0.7785, 0.4375, 0.0590, 0.4073, 0.1309, 0.6407, 0.8286,
         0.7780],
        [0.1487, 0.4422, 0.5434, 0.4459, 0.2418, 0.1178, 0.3292, 0.8791, 0.0865,
         0.5309],
        [0.8617, 0.7253, 0.7221, 0.1586, 0.8773, 0.4278, 0.7801, 0.9021, 0.5468,
         0.0678]])

In [83]:
random_tensor.ndim

2

In [84]:
random_images_sizes_tensors = torch.rand(size=(224, 224)) # hight, weight, colour channel (R, G, B)
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224]), 2)

In [85]:
random_images_sizes_tensors = torch.rand(size=(224, 224, 3))
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224, 3]), 3)

In [86]:
torch.rand(3, 3)

tensor([[0.3426, 0.3740, 0.6355],
        [0.3915, 0.4910, 0.3561],
        [0.6250, 0.3859, 0.4541]])

## Zeros and Ones

In [87]:
# Create tensorn all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [88]:
# Create tensorn all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [89]:
ones.dtype # data types

torch.float32

In [90]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [91]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
one_to_ten = torch.arange(start=0, end=1000, step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [93]:
# createing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors data types

In [94]:
# Float 32 tensors
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,  # what datatype is the tensor (float32, float16)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensors

tensor([3., 6., 9.])

In [95]:
float_32_tensors.dtype

torch.float32

In [96]:
float16_tensors = float_32_tensors.type(torch.float16)
float16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [97]:
float16_tensors * float_32_tensors

tensor([ 9., 36., 81.])

In [98]:
int_32_tensors = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensors

tensor([3, 6, 9])

In [99]:
float16_tensors * int_32_tensors

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting infprmation from tensors

In [100]:
# create a tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4002, 0.0693, 0.4543, 0.3948],
        [0.6377, 0.1737, 0.0135, 0.9943],
        [0.5225, 0.5743, 0.2335, 0.7830]])

In [101]:
some_tensor.size()

torch.Size([3, 4])

In [102]:
# find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4002, 0.0693, 0.4543, 0.3948],
        [0.6377, 0.1737, 0.0135, 0.9943],
        [0.5225, 0.5743, 0.2335, 0.7830]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensors operations)

involve fundamental arithmetic (addition, multiplication) element-wise or via matrix/tensor products, plus advanced functions like reshaping, transposing, indexing, and slicing


In [103]:
# create a tensors and 10 to it
tensors = torch.tensor([1, 2, 3])
tensors + 10


tensor([11, 12, 13])

In [104]:
# Multiply by 10
tensors * 10

tensor([10, 20, 30])

In [105]:
tensors

tensor([1, 2, 3])

In [106]:
tensors - 10

tensor([-9, -8, -7])

In [107]:
torch.mul(tensors, 10)

tensor([10, 20, 30])

In [108]:
torch.add(tensors, 10)

tensor([11, 12, 13])

### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is[ matrix multiplication](https://https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on i

In [109]:
# element
print(tensors, "*", tensors)
print(f"Equals: {tensors * tensors}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [110]:
# Matrix
torch.matmul(tensors, tensors)

tensor(14)

In [111]:
tensors

tensor([1, 2, 3])

In [112]:
# Matrix by hand
1*1 + 2*2 + 3*3

14

In [113]:
%%time
value = 0
for i in range(len(tensors)):
  value += tensors[i] * tensors[i]
print(value)

tensor(14)
CPU times: user 853 µs, sys: 0 ns, total: 853 µs
Wall time: 861 µs


In [114]:
%%time
torch.matmul(tensors, tensors)

CPU times: user 329 µs, sys: 22 µs, total: 351 µs
Wall time: 291 µs


tensor(14)

### one of most commen error in the deep learing: shape Error

http://matrixmultiplication.xyz/

In [115]:
# sahpe for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [116]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [118]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [120]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [124]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])