In [51]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


Introduction Tesors

creating tensors

torch.Tensor -> https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor

In [52]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [53]:
scalar.ndim

0

In [54]:
# Get tensor back as python init
scalar.item()

7

In [55]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [56]:
vector.ndim

1

In [57]:
vector.shape

torch.Size([2])

In [58]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [59]:
MATRIX.ndim

2

In [60]:
MATRIX[1]

tensor([ 9, 10])

In [61]:
MATRIX.shape

torch.Size([2, 2])

In [62]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [63]:
TENSOR.ndim

3

In [64]:
TENSOR.shape

torch.Size([1, 3, 3])

In [65]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [66]:
5*10*10

500

In [67]:
## Creating random tensors of sizes
random_tensor = torch.rand(5, 10)
random_tensor

tensor([[0.0916, 0.2827, 0.1371, 0.5423, 0.1631, 0.5080, 0.9315, 0.4525, 0.4265,
         0.8239],
        [0.7769, 0.0668, 0.6833, 0.3379, 0.2583, 0.9063, 0.4357, 0.3608, 0.5668,
         0.1921],
        [0.3817, 0.1792, 0.4211, 0.9888, 0.6837, 0.6686, 0.8878, 0.4432, 0.2283,
         0.9987],
        [0.2165, 0.1719, 0.7795, 0.7442, 0.7151, 0.7217, 0.5712, 0.3815, 0.0666,
         0.8363],
        [0.8213, 0.6115, 0.9536, 0.2517, 0.7523, 0.3528, 0.4466, 0.1541, 0.9724,
         0.6223]])

In [68]:
random_tensor.ndim

2

In [69]:
random_images_sizes_tensors = torch.rand(size=(224, 224)) # hight, weight, colour channel (R, G, B)
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224]), 2)

In [70]:
random_images_sizes_tensors = torch.rand(size=(224, 224, 3))
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224, 3]), 3)

In [71]:
torch.rand(3, 3)

tensor([[0.2490, 0.7567, 0.3985],
        [0.8261, 0.6497, 0.3510],
        [0.1104, 0.2442, 0.8182]])

## Zeros and Ones

In [72]:
# Create tensorn all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [73]:
# Create tensorn all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
ones.dtype # data types

torch.float32

In [75]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [76]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
one_to_ten = torch.arange(start=0, end=1000, step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [78]:
# createing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors data types

In [79]:
# Float 32 tensors
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,  # what datatype is the tensor (float32, float16)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensors

tensor([3., 6., 9.])

In [80]:
float_32_tensors.dtype

torch.float32

In [81]:
float16_tensors = float_32_tensors.type(torch.float16)
float16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [82]:
float16_tensors * float_32_tensors

tensor([ 9., 36., 81.])

In [83]:
int_32_tensors = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensors

tensor([3, 6, 9])

In [84]:
float16_tensors * int_32_tensors

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting infprmation from tensors

In [85]:
# create a tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9017, 0.9737, 0.5240, 0.9390],
        [0.3598, 0.3893, 0.5478, 0.0212],
        [0.5195, 0.0598, 0.3702, 0.2828]])

In [86]:
some_tensor.size()

torch.Size([3, 4])

In [87]:
# find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9017, 0.9737, 0.5240, 0.9390],
        [0.3598, 0.3893, 0.5478, 0.0212],
        [0.5195, 0.0598, 0.3702, 0.2828]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensors operations)

involve fundamental arithmetic (addition, multiplication) element-wise or via matrix/tensor products, plus advanced functions like reshaping, transposing, indexing, and slicing


In [88]:
# create a tensors and 10 to it
tensors = torch.tensor([1, 2, 3])
tensors + 10


tensor([11, 12, 13])

In [89]:
# Multiply by 10
tensors * 10

tensor([10, 20, 30])

In [90]:
tensors

tensor([1, 2, 3])

In [91]:
tensors - 10

tensor([-9, -8, -7])

In [92]:
torch.mul(tensors, 10)

tensor([10, 20, 30])

In [93]:
torch.add(tensors, 10)

tensor([11, 12, 13])

### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is[ matrix multiplication](https://https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on i

In [94]:
# element
print(tensors, "*", tensors)
print(f"Equals: {tensors * tensors}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [95]:
# Matrix
torch.matmul(tensors, tensors)

tensor(14)

In [96]:
tensors

tensor([1, 2, 3])

In [97]:
# Matrix by hand
1*1 + 2*2 + 3*3

14

In [98]:
%%time
value = 0
for i in range(len(tensors)):
  value += tensors[i] * tensors[i]
print(value)

tensor(14)
CPU times: user 1.14 ms, sys: 17 µs, total: 1.16 ms
Wall time: 1.76 ms


In [99]:
%%time
torch.matmul(tensors, tensors)

CPU times: user 148 µs, sys: 18 µs, total: 166 µs
Wall time: 129 µs


tensor(14)

### one of most commen error in the deep learing: shape Error

http://matrixmultiplication.xyz/

In [100]:
# sahpe for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [101]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [102]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [103]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [104]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [106]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensors aggregation)

In [114]:
# create a tensors
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [110]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [111]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [116]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [117]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))