# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch


# Create random tensor
torch_rand = torch.rand(7, 7)
print(torch_rand)


tensor([[0.2879, 0.4922, 0.7104, 0.6569, 0.6395, 0.0745, 0.4086],
        [0.8782, 0.8275, 0.7933, 0.8848, 0.0105, 0.1624, 0.9679],
        [0.8966, 0.0323, 0.7169, 0.0322, 0.6126, 0.5014, 0.2679],
        [0.8394, 0.1083, 0.7299, 0.7696, 0.7886, 0.4796, 0.6030],
        [0.3004, 0.4296, 0.8554, 0.4597, 0.6226, 0.6213, 0.2801],
        [0.6059, 0.9272, 0.8771, 0.1922, 0.1485, 0.2028, 0.5651],
        [0.0651, 0.9616, 0.4118, 0.2391, 0.2720, 0.9102, 0.5841]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [18]:
# Create another random tensor
torch_rand2 = torch.rand(7, 1)

# Perform matrix multiplication 
torch_matmul = torch.mm(torch_rand, torch_rand2)
print(torch_matmul)


tensor([[2.1975],
        [2.4672],
        [1.8472],
        [2.8928],
        [2.5215],
        [1.8183],
        [2.2787]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [15]:
# Set manual seed
torch.manual_seed(0)

# Create random tensor
tensor_A = torch.rand(7, 7)

# Create another random tensor
tensor_B = torch.rand(1, 7)

# Matrix multiply tensors (transpose tensor_B to make shapes compatible)
tensor_C = torch.mm(tensor_A, tensor_B.T)
print(tensor_C, tensor_C.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [19]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(0)
    



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed



# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
