In [99]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cu126


Introduction Tesors

creating tensors

torch.Tensor -> https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor

In [100]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [101]:
scalar.ndim

0

In [102]:
# Get tensor back as python init
scalar.item()

7

In [103]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [104]:
vector.ndim

1

In [105]:
vector.shape

torch.Size([2])

In [106]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [107]:
MATRIX.ndim

2

In [108]:
MATRIX[1]

tensor([ 9, 10])

In [109]:
MATRIX.shape

torch.Size([2, 2])

In [110]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [111]:
TENSOR.ndim

3

In [112]:
TENSOR.shape

torch.Size([1, 3, 3])

In [113]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [114]:
5*10*10

500

In [115]:
## Creating random tensors of sizes
random_tensor = torch.rand(5, 10)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696,
         0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516,
         0.0753],
        [0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343,
         0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050,
         0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315,
         0.1587]])

In [116]:
random_tensor.ndim

2

In [117]:
random_images_sizes_tensors = torch.rand(size=(224, 224)) # hight, weight, colour channel (R, G, B)
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224]), 2)

In [118]:
random_images_sizes_tensors = torch.rand(size=(224, 224, 3))
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224, 3]), 3)

In [119]:
torch.rand(3, 3)

tensor([[0.3592, 0.0866, 0.4388],
        [0.5499, 0.2435, 0.5170],
        [0.5769, 0.4577, 0.6093]])

## Zeros and Ones

In [120]:
# Create tensorn all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [121]:
# Create tensorn all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
ones.dtype # data types

torch.float32

In [123]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [124]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
one_to_ten = torch.arange(start=0, end=1000, step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [126]:
# createing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors data types

In [127]:
# Float 32 tensors
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,  # what datatype is the tensor (float32, float16)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensors

tensor([3., 6., 9.])

In [128]:
float_32_tensors.dtype

torch.float32

In [129]:
float16_tensors = float_32_tensors.type(torch.float16)
float16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [130]:
float16_tensors * float_32_tensors

tensor([ 9., 36., 81.])

In [131]:
int_32_tensors = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensors

tensor([3, 6, 9])

In [132]:
float16_tensors * int_32_tensors

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting infprmation from tensors

In [133]:
# create a tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1802, 0.9330, 0.8854, 0.1516],
        [0.5473, 0.5933, 0.3490, 0.1653],
        [0.1777, 0.0861, 0.5978, 0.6043]])

In [134]:
some_tensor.size()

torch.Size([3, 4])

In [135]:
# find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1802, 0.9330, 0.8854, 0.1516],
        [0.5473, 0.5933, 0.3490, 0.1653],
        [0.1777, 0.0861, 0.5978, 0.6043]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensors operations)

involve fundamental arithmetic (addition, multiplication) element-wise or via matrix/tensor products, plus advanced functions like reshaping, transposing, indexing, and slicing


In [136]:
# create a tensors and 10 to it
tensors = torch.tensor([1, 2, 3])
tensors + 10


tensor([11, 12, 13])

In [137]:
# Multiply by 10
tensors * 10

tensor([10, 20, 30])

In [138]:
tensors

tensor([1, 2, 3])

In [139]:
tensors - 10

tensor([-9, -8, -7])

In [140]:
torch.mul(tensors, 10)

tensor([10, 20, 30])

In [141]:
torch.add(tensors, 10)

tensor([11, 12, 13])

### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is[ matrix multiplication](https://https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on i
![image.png](https://camo.githubusercontent.com/c4cbd81b1bf62e64a6ea9db18880e7da8e947cfdc4e33c86151a09133b2d4d0a/68747470733a2f2f6769746875622e636f6d2f6d7264626f75726b652f7079746f7263682d646565702d6c6561726e696e672f7261772f6d61696e2f696d616765732f30302d6d61747269782d6d756c7469706c792d63726f702e676966)

In [142]:
# element
print(tensors, "*", tensors)
print(f"Equals: {tensors * tensors}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [143]:
# Matrix
torch.matmul(tensors, tensors)

tensor(14)

In [144]:
tensors

tensor([1, 2, 3])

In [145]:
# Matrix by hand
1*1 + 2*2 + 3*3

14

In [146]:
%%time
value = 0
for i in range(len(tensors)):
  value += tensors[i] * tensors[i]
print(value)

tensor(14)
CPU times: user 936 µs, sys: 0 ns, total: 936 µs
Wall time: 1.72 ms


In [147]:
%%time
torch.matmul(tensors, tensors)

CPU times: user 367 µs, sys: 0 ns, total: 367 µs
Wall time: 312 µs


tensor(14)

### one of most commen error in the deep learing: shape Error

http://matrixmultiplication.xyz/

In [148]:
# sahpe for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul

In [149]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [150]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [151]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [152]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [153]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensors aggregation)

In [154]:
# create a tensors
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [155]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [156]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [157]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [158]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Find the positional min and max

In [159]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [160]:
# Find the positions in a tensor that has the minimum value with argmin() => return index
x.argmin()

tensor(0)

In [161]:
x[0]

tensor(1)

In [162]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [163]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

| Method | One-line description |
|-------|----------------------|
| `torch.reshape(input, shape)` | Reshapes `input` to `shape` (if compatible); can also use `torch.Tensor.reshape()` |
| `Tensor.view(shape)` | Returns a view of the original tensor in a different shape, sharing the same underlying data |
| `torch.stack(tensors, dim=0)` | Concatenates a sequence of tensors along a **new** dimension `dim`; all tensors must have the same size |
| `torch.squeeze(input)` | Removes all dimensions of size `1` from the tensor |
| `torch.unsqueeze(input, dim)` | Adds a dimension of size `1` at the specified `dim` |
| `torch.permute(input, dims)` | Returns a view of the tensor with its dimensions rearranged according to `dims` |



In [164]:
# Create a tensors
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [165]:
# Add a extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [166]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [167]:
# changes z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [168]:
# Stack tensors on the top of each orthers
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [169]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [170]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [171]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channel]

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [172]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (Select data from tensors)
indexing with pythorch is similer to indexing with numpy

In [173]:
# Create a tensors
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [174]:
# Let index on our new tensors
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [175]:
# let index on the middel bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [176]:
# Lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [177]:
x[0][2][2]

tensor(9)

In [178]:
# we can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [179]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [180]:
x[:, 2, 2]

tensor([9])

In [181]:
# Get index 0 of 0th and 1st dimnsion and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [182]:
# Index on return on number 9
x[:, 2, 2]

# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

In [183]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Pythorch tensors and numpy


In [184]:
# numpy array
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensors = torch.from_numpy(array)
array, tensors

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [185]:
array.dtype

dtype('float64')

In [186]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [187]:
array = array + 1
array, tensors

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [188]:
# TENSORS TO NUMPY
tensors = torch.ones(7)
numpy_tensors = tensors.numpy()
tensors, numpy_tensors

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (traying to take random out of random)

In [189]:
import torch
# Create two random numbers
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1200, 0.9837, 0.2071, 0.7188],
        [0.2992, 0.3965, 0.8485, 0.8707],
        [0.3635, 0.5419, 0.3250, 0.0410]])
tensor([[0.7282, 0.6979, 0.7753, 0.9788],
        [0.6804, 0.6861, 0.1259, 0.0489],
        [0.8675, 0.7867, 0.1907, 0.0884]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [190]:
# leats make random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pyTorch object on the GPU (and making faster computations)

In [191]:
!nvidia-smi

Wed Dec 31 01:15:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             10W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. check for gpu access with pyTorch

In [192]:
## check for gpu acess with pythorch
import torch
torch.cuda.is_available()

True

In [193]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## 3 .Putting tensors on the GPU
The reason we want to put tensors on the GPU is that GPUs are specialized hardware designed to accelerate the types of mathematical operations that deep learning relies on, such as matrix multiplications and convolutions. By leveraging the parallel processing capabilities of GPUs, we can significantly speed up the training and inference of deep learning models compared to using a CPU alone.

In [196]:
# create a tensor (by default on the cpu)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [198]:
# Move tensor to the gpu (if available)
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu)

tensor([1, 2, 3], device='cuda:0')


### 4. Moving Tensors back to the Cpu

In [201]:
# to fix GPU tensors with numpy issue, move tensor back to cpu first
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [202]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')