In [93]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


Introduction Tesors

creating tensors

torch.Tensor -> https://docs.pytorch.org/docs/stable/tensors.html#torch-tensor

In [94]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [95]:
scalar.ndim

0

In [96]:
# Get tensor back as python init
scalar.item()

7

In [97]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [98]:
vector.ndim

1

In [99]:
vector.shape

torch.Size([2])

In [100]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [101]:
MATRIX.ndim

2

In [102]:
MATRIX[1]

tensor([ 9, 10])

In [103]:
MATRIX.shape

torch.Size([2, 2])

In [104]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [105]:
TENSOR.ndim

3

In [106]:
TENSOR.shape

torch.Size([1, 3, 3])

In [107]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [108]:
5*10*10

500

In [109]:
## Creating random tensors of sizes
random_tensor = torch.rand(5, 10)
random_tensor

tensor([[0.9937, 0.0496, 0.4043, 0.9569, 0.8202, 0.4135, 0.2194, 0.2683, 0.4134,
         0.2224],
        [0.4287, 0.3493, 0.5074, 0.7114, 0.0180, 0.6073, 0.7293, 0.3220, 0.5653,
         0.8802],
        [0.2479, 0.9549, 0.8996, 0.2078, 0.4456, 0.3613, 0.6230, 0.1710, 0.8096,
         0.9479],
        [0.9923, 0.3579, 0.4893, 0.7433, 0.0734, 0.4193, 0.4167, 0.7358, 0.1017,
         0.6147],
        [0.1307, 0.6680, 0.2212, 0.9723, 0.3113, 0.9942, 0.2299, 0.0591, 0.4667,
         0.8113]])

In [110]:
random_tensor.ndim

2

In [111]:
random_images_sizes_tensors = torch.rand(size=(224, 224)) # hight, weight, colour channel (R, G, B)
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224]), 2)

In [112]:
random_images_sizes_tensors = torch.rand(size=(224, 224, 3))
random_images_sizes_tensors.shape, random_images_sizes_tensors.ndim

(torch.Size([224, 224, 3]), 3)

In [113]:
torch.rand(3, 3)

tensor([[0.4423, 0.0185, 0.4022],
        [0.4544, 0.3943, 0.0560],
        [0.2070, 0.6163, 0.0437]])

## Zeros and Ones

In [114]:
# Create tensorn all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [115]:
# Create tensorn all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [116]:
ones.dtype # data types

torch.float32

In [117]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [118]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
one_to_ten = torch.arange(start=0, end=1000, step=50)
one_to_ten

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [120]:
# createing tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors data types

In [121]:
# Float 32 tensors
float_32_tensors = torch.tensor([3.0, 6.0, 9.0],
                                dtype=None,  # what datatype is the tensor (float32, float16)
                                device=None, # what device is your tensor on
                                requires_grad=False) # whether or not to track gradients with this tensors operations

float_32_tensors

tensor([3., 6., 9.])

In [122]:
float_32_tensors.dtype

torch.float32

In [123]:
float16_tensors = float_32_tensors.type(torch.float16)
float16_tensors

tensor([3., 6., 9.], dtype=torch.float16)

In [124]:
float16_tensors * float_32_tensors

tensor([ 9., 36., 81.])

In [125]:
int_32_tensors = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensors

tensor([3, 6, 9])

In [126]:
float16_tensors * int_32_tensors

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting infprmation from tensors

In [127]:
# create a tensors
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2388, 0.9533, 0.8075, 0.7463],
        [0.0215, 0.5571, 0.2443, 0.2136],
        [0.2685, 0.8422, 0.7143, 0.5149]])

In [128]:
some_tensor.size()

torch.Size([3, 4])

In [129]:
# find out details about some tensors
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2388, 0.9533, 0.8075, 0.7463],
        [0.0215, 0.5571, 0.2443, 0.2136],
        [0.2685, 0.8422, 0.7143, 0.5149]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensors operations)

involve fundamental arithmetic (addition, multiplication) element-wise or via matrix/tensor products, plus advanced functions like reshaping, transposing, indexing, and slicing


In [130]:
# create a tensors and 10 to it
tensors = torch.tensor([1, 2, 3])
tensors + 10


tensor([11, 12, 13])

In [131]:
# Multiply by 10
tensors * 10

tensor([10, 20, 30])

In [132]:
tensors

tensor([1, 2, 3])

In [133]:
tensors - 10

tensor([-9, -8, -7])

In [134]:
torch.mul(tensors, 10)

tensor([10, 20, 30])

In [135]:
torch.add(tensors, 10)

tensor([11, 12, 13])

### Matrix multiplication (is all you need)
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is[ matrix multiplication](https://https://www.mathsisfun.com/algebra/matrix-multiplying.html).

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

The resulting matrix has the shape of the outer dimensions:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

Resource: You can see all of the rules for matrix multiplication using torch.matmul() in the PyTorch documentation.

Let's create a tensor and perform element-wise multiplication and matrix multiplication on i
![image.png](https://camo.githubusercontent.com/c4cbd81b1bf62e64a6ea9db18880e7da8e947cfdc4e33c86151a09133b2d4d0a/68747470733a2f2f6769746875622e636f6d2f6d7264626f75726b652f7079746f7263682d646565702d6c6561726e696e672f7261772f6d61696e2f696d616765732f30302d6d61747269782d6d756c7469706c792d63726f702e676966)

In [136]:
# element
print(tensors, "*", tensors)
print(f"Equals: {tensors * tensors}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [137]:
# Matrix
torch.matmul(tensors, tensors)

tensor(14)

In [138]:
tensors

tensor([1, 2, 3])

In [139]:
# Matrix by hand
1*1 + 2*2 + 3*3

14

In [140]:
%%time
value = 0
for i in range(len(tensors)):
  value += tensors[i] * tensors[i]
print(value)

tensor(14)
CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 1.91 ms


In [141]:
%%time
torch.matmul(tensors, tensors)

CPU times: user 574 µs, sys: 0 ns, total: 574 µs
Wall time: 680 µs


tensor(14)

### one of most commen error in the deep learing: shape Error

http://matrixmultiplication.xyz/

In [142]:
# sahpe for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for torch.matmul

In [143]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [144]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [145]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [146]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [147]:
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensors aggregation)

In [148]:
# create a tensors
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [149]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [150]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [151]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [152]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Find the positional min and max

In [153]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [154]:
# Find the positions in a tensor that has the minimum value with argmin() => return index
x.argmin()

tensor(0)

In [155]:
x[0]

tensor(1)

In [156]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [157]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing tensors

| Method | One-line description |
|-------|----------------------|
| `torch.reshape(input, shape)` | Reshapes `input` to `shape` (if compatible); can also use `torch.Tensor.reshape()` |
| `Tensor.view(shape)` | Returns a view of the original tensor in a different shape, sharing the same underlying data |
| `torch.stack(tensors, dim=0)` | Concatenates a sequence of tensors along a **new** dimension `dim`; all tensors must have the same size |
| `torch.squeeze(input)` | Removes all dimensions of size `1` from the tensor |
| `torch.unsqueeze(input, dim)` | Adds a dimension of size `1` at the specified `dim` |
| `torch.permute(input, dims)` | Returns a view of the tensor with its dimensions rearranged according to `dims` |



In [158]:
# Create a tensors
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [159]:
# Add a extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [160]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [161]:
# changes z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [162]:
# Stack tensors on the top of each orthers
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [163]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [164]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [165]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channel]

x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [166]:
x_original[0, 0, 0] = 728218
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(728218.), tensor(728218.))

### Indexing (Select data from tensors)
indexing with pythorch is similer to indexing with numpy

In [167]:
# Create a tensors
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [168]:
# Let index on our new tensors
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [169]:
# let index on the middel bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [170]:
# Lets index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [171]:
x[0][2][2]

tensor(9)

In [172]:
# we can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [173]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [174]:
x[:, 2, 2]

tensor([9])

In [175]:
# Get index 0 of 0th and 1st dimnsion and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [176]:
# Index on return on number 9
x[:, 2, 2]

# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

In [177]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## Pythorch tensors and numpy


In [178]:
# numpy array
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensors = torch.from_numpy(array)
array, tensors

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [179]:
array.dtype

dtype('float64')

In [180]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [181]:
array = array + 1
array, tensors

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [182]:
# TENSORS TO NUMPY
tensors = torch.ones(7)
numpy_tensors = tensors.numpy()
tensors, numpy_tensors

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (traying to take random out of random)

In [184]:
import torch
# Create two random numbers
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8087, 0.3019, 0.4107, 0.0946],
        [0.9935, 0.4671, 0.7469, 0.1777],
        [0.9969, 0.6450, 0.0444, 0.7878]])
tensor([[0.5514, 0.0672, 0.9717, 0.7540],
        [0.2675, 0.9723, 0.7454, 0.8676],
        [0.8454, 0.5956, 0.7364, 0.1136]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


True